version: '3.8'

services:
  my_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: yashv
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  golang_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - my_db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: my_db
      DB_PORT: 5432
      DB_USER: yashv
      DB_PASSWORD: admin
      DB_NAME: library
    command: ["./wait-for-it.sh", "my_db:5432", "--", "./main"]

volumes:
  postgres-data:
